/*
 * This Java source file was generated by the Gradle 'init' task.
 * to run 'gradle run'
 */
package ju.video.player;
import java.text.ParseException;

import ju.video.player.view.playlist.PlayListFrame;

import java.io.IOException;

public class App {
    public static void main(String[] args) throws IOException, ParseException {
        new PlayListFrame();
    }
}
